### ISSUE TITLE
wrong points generated

### ISSUE THREAD

**Issue by dyxwxjdy** [yasuohasegawa/SVGPainterUnity#1]
d="M367 32C368.489 50.869 369 70.0534 369 89C369 94.9768 371.435 104.399 369.106 109.871C367.389 113.904 362.109 116.091 359.09 119.09

more points generated than the same data in Illustrator

![image](https://user-images.githubusercontent.com/21116534/227323780-3fb37db9-f73b-4dec-88bc-2845b2860b0b.png)

**Comment by dyxwxjdy** [comment]
trim solve problem

**Comment by dyxwxjdy** [comment]
in Illustrator it looks like:

![image](https://user-images.githubusercontent.com/21116534/227324172-22109e67-1760-472b-9192-b15a5fff9ca7.png)

**Comment by yasuohasegawa** [comment]
Sorry, I'm quite busy with the projects. I'll take a look at the issues when things settle down for me.

**Comment by dyxwxjdy** [comment]
hi I figure out what happened.

bug at SVGPainter.cs :
val = val.Replace(item.Value, item.Value + " ");

if input is 116.091 359.09 119.09,  replace "09" of "116.091" will make it "116.09 1"

so I make some change and solves

```
	for (int i = 0; i < mc.Count; i++)
	{
		Match item = mc[i];
		UnityEngine.Debug.Log(item);
		val = val.Insert(item.Index + i + item.Value.Length, " ");
		//val = val.Replace(item.Value, item.Value + " "); //bug line
	}
```
